<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SistemReserva.Domain\SistemReserva.Domain.csproj" />
    <ProjectReference Include="..\SistemReserva.Infrastructure\SistemReserva.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Reservas\GetReservas\" />
    <Folder Include="Reservas\DeleteReserva\" />
    <Folder Include="Reservas\UpdateReserva\" />
  </ItemGroup>

</Project>
